[env:feather]
platform = espressif32
board = adafruit_feather_esp32s3_reversetft
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit ST7735 and ST7789 Library
  adafruit/Adafruit GFX Library
  adafruit/Adafruit BusIO
  s00500/ESPUI
  bblanchon/ArduinoJson @ ^6.21.5
check_tool = cppcheck, clangtidy
check_skip_packages = yes
check_src_filters =
  +<src/>
check_flags =
  cppcheck: --enable=style --inline-suppr
